[2023-04-02 18:47:43,319] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [queued]>
[2023-04-02 18:47:43,333] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [queued]>
[2023-04-02 18:47:43,334] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 18:47:43,334] {taskinstance.py:1069} INFO - Starting attempt 27 of 32
[2023-04-02 18:47:43,335] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 18:47:43,341] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): process_data> on 2023-04-01T00:00:00+00:00
[2023-04-02 18:47:43,349] {standard_task_runner.py:52} INFO - Started process 3774 to run task
[2023-04-02 18:47:43,357] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_weather_etl_v02', 'process_data', '2023-04-01T00:00:00+00:00', '--job-id', '224', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_weather.py', '--cfg-path', '/tmp/tmpa4rzsmy6', '--error-file', '/tmp/tmpwgdtg0pw']
[2023-04-02 18:47:43,361] {standard_task_runner.py:77} INFO - Job 224: Subtask process_data
[2023-04-02 18:47:43,476] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [running]> on host b24fa9ddb366
[2023-04-02 18:47:43,573] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mario
AIRFLOW_CTX_DAG_ID=dag_weather_etl_v02
AIRFLOW_CTX_TASK_ID=process_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-01T00:00:00+00:00
[2023-04-02 18:47:52,254] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py:238 FutureWarning: Python 3.6 support is deprecated in Spark 3.2.
[2023-04-02 18:47:55,430] {logging_mixin.py:104} INFO - There are NaN values in the data!
[2023-04-02 18:47:55,433] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_weather.py", line 55, in process_data
    datos = datos.replace(np.na, '', regex=True)
AttributeError: module 'numpy' has no attribute 'na'
[2023-04-02 18:47:55,437] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_weather_etl_v02, task_id=process_data, execution_date=20230401T000000, start_date=20230402T184743, end_date=20230402T184755
[2023-04-02 18:47:55,541] {local_task_job.py:146} INFO - Task exited with return code 1
