[2023-04-02 19:08:30,962] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [queued]>
[2023-04-02 19:08:30,984] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [queued]>
[2023-04-02 19:08:30,987] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 19:08:30,989] {taskinstance.py:1069} INFO - Starting attempt 31 of 32
[2023-04-02 19:08:30,990] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 19:08:31,016] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): process_data> on 2023-04-01T00:00:00+00:00
[2023-04-02 19:08:31,036] {standard_task_runner.py:52} INFO - Started process 6892 to run task
[2023-04-02 19:08:31,044] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_weather_etl_v02', 'process_data', '2023-04-01T00:00:00+00:00', '--job-id', '245', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_weather.py', '--cfg-path', '/tmp/tmpvc4b7pdk', '--error-file', '/tmp/tmpd3ft1y5d']
[2023-04-02 19:08:31,045] {standard_task_runner.py:77} INFO - Job 245: Subtask process_data
[2023-04-02 19:08:31,123] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [running]> on host b24fa9ddb366
[2023-04-02 19:08:31,192] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mario
AIRFLOW_CTX_DAG_ID=dag_weather_etl_v02
AIRFLOW_CTX_TASK_ID=process_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-01T00:00:00+00:00
[2023-04-02 19:08:38,015] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py:238 FutureWarning: Python 3.6 support is deprecated in Spark 3.2.
[2023-04-02 19:08:39,393] {logging_mixin.py:104} INFO - There are NaN values in the data!
[2023-04-02 19:08:39,420] {logging_mixin.py:104} INFO - La fecha 02/04/2023 19:00 no tiene el formato correcto
[2023-04-02 19:08:39,421] {logging_mixin.py:104} INFO - La fecha 02/04/2023 18:00 no tiene el formato correcto
[2023-04-02 19:08:39,421] {logging_mixin.py:104} INFO - La fecha 02/04/2023 17:00 no tiene el formato correcto
[2023-04-02 19:08:39,422] {logging_mixin.py:104} INFO - La fecha 02/04/2023 16:00 no tiene el formato correcto
[2023-04-02 19:08:39,423] {logging_mixin.py:104} INFO - La fecha 02/04/2023 15:00 no tiene el formato correcto
[2023-04-02 19:08:39,424] {logging_mixin.py:104} INFO - La fecha 02/04/2023 14:00 no tiene el formato correcto
[2023-04-02 19:08:39,424] {logging_mixin.py:104} INFO - La fecha 02/04/2023 13:00 no tiene el formato correcto
[2023-04-02 19:08:39,425] {logging_mixin.py:104} INFO - La fecha 02/04/2023 12:00 no tiene el formato correcto
[2023-04-02 19:08:39,425] {logging_mixin.py:104} INFO - La fecha 02/04/2023 11:00 no tiene el formato correcto
[2023-04-02 19:08:39,426] {logging_mixin.py:104} INFO - La fecha 02/04/2023 10:00 no tiene el formato correcto
[2023-04-02 19:08:39,427] {logging_mixin.py:104} INFO - La fecha 02/04/2023 09:00 no tiene el formato correcto
[2023-04-02 19:08:39,427] {logging_mixin.py:104} INFO - La fecha 02/04/2023 08:00 no tiene el formato correcto
[2023-04-02 19:08:39,428] {logging_mixin.py:104} INFO - La fecha 02/04/2023 07:00 no tiene el formato correcto
[2023-04-02 19:08:39,428] {logging_mixin.py:104} INFO - La fecha 02/04/2023 06:00 no tiene el formato correcto
[2023-04-02 19:08:39,429] {logging_mixin.py:104} INFO - La fecha 02/04/2023 05:00 no tiene el formato correcto
[2023-04-02 19:08:39,430] {logging_mixin.py:104} INFO - La fecha 02/04/2023 04:00 no tiene el formato correcto
[2023-04-02 19:08:39,430] {logging_mixin.py:104} INFO - La fecha 02/04/2023 03:00 no tiene el formato correcto
[2023-04-02 19:08:39,431] {logging_mixin.py:104} INFO - La fecha 02/04/2023 02:00 no tiene el formato correcto
[2023-04-02 19:08:39,432] {logging_mixin.py:104} INFO - La fecha 02/04/2023 01:00 no tiene el formato correcto
[2023-04-02 19:08:39,433] {logging_mixin.py:104} INFO - La fecha 02/04/2023 00:00 no tiene el formato correcto
[2023-04-02 19:08:39,433] {logging_mixin.py:104} INFO - La fecha 01/04/2023 23:00 no tiene el formato correcto
[2023-04-02 19:08:39,434] {logging_mixin.py:104} INFO - La fecha 01/04/2023 22:00 no tiene el formato correcto
[2023-04-02 19:08:39,435] {logging_mixin.py:104} INFO - La fecha 01/04/2023 21:00 no tiene el formato correcto
[2023-04-02 19:08:39,435] {logging_mixin.py:104} INFO - La fecha 01/04/2023 20:00 no tiene el formato correcto
[2023-04-02 19:08:40,072] {logging_mixin.py:104} WARNING - Traceback (most recent call last):
[2023-04-02 19:08:40,075] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/serializers.py", line 437, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
[2023-04-02 19:08:40,076] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
[2023-04-02 19:08:40,076] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
[2023-04-02 19:08:40,077] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
[2023-04-02 19:08:40,079] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 19:08:40,080] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
[2023-04-02 19:08:40,081] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 19:08:40,082] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
[2023-04-02 19:08:40,084] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 682, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
[2023-04-02 19:08:40,086] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
[2023-04-02 19:08:40,087] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 19:08:40,088] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
[2023-04-02 19:08:40,088] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 19:08:40,089] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
[2023-04-02 19:08:40,090] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 19:08:40,091] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/dill/_dill.py", line 1169, in save_cell
    f = obj.cell_contents
[2023-04-02 19:08:40,092] {logging_mixin.py:104} WARNING - ValueError: Cell is empty
[2023-04-02 19:08:40,096] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/serializers.py", line 437, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/usr/local/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 682, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
  File "/usr/local/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/airflow/.local/lib/python3.6/site-packages/dill/_dill.py", line 1169, in save_cell
    f = obj.cell_contents
ValueError: Cell is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_weather.py", line 78, in process_data
    spark_df = (spark.createDataFrame(datos_procesados))
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 674, in createDataFrame
    data, schema, samplingRatio, verifySchema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/pandas/conversion.py", line 340, in createDataFrame
    return self._create_dataframe(data, schema, samplingRatio, verifySchema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 701, in _create_dataframe
    jrdd = self._jvm.SerDeUtil.toJavaArray(rdd._to_java_object_rdd())
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/rdd.py", line 2620, in _to_java_object_rdd
    return self.ctx._jvm.SerDeUtil.pythonToJava(rdd._jrdd, True)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/rdd.py", line 2952, in _jrdd
    self._jrdd_deserializer, profiler)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/rdd.py", line 2830, in _wrap_function
    pickled_command, broadcast_vars, env, includes = _prepare_for_python_RDD(sc, command)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/rdd.py", line 2816, in _prepare_for_python_RDD
    pickled_command = ser.dumps(command)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/serializers.py", line 447, in dumps
    raise pickle.PicklingError(msg)
_pickle.PicklingError: Could not serialize object: ValueError: Cell is empty
[2023-04-02 19:08:40,116] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_weather_etl_v02, task_id=process_data, execution_date=20230401T000000, start_date=20230402T190830, end_date=20230402T190840
[2023-04-02 19:08:41,066] {local_task_job.py:146} INFO - Task exited with return code 1
