[2023-04-02 17:33:34,931] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [queued]>
[2023-04-02 17:33:34,969] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [queued]>
[2023-04-02 17:33:34,971] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 17:33:34,972] {taskinstance.py:1069} INFO - Starting attempt 5 of 10
[2023-04-02 17:33:34,973] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 17:33:34,990] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): process_data> on 2023-04-01T00:00:00+00:00
[2023-04-02 17:33:35,040] {standard_task_runner.py:52} INFO - Started process 493 to run task
[2023-04-02 17:33:35,049] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_weather_etl_v02', 'process_data', '2023-04-01T00:00:00+00:00', '--job-id', '202', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_weather.py', '--cfg-path', '/tmp/tmp8_9jus4m', '--error-file', '/tmp/tmptisw1vuz']
[2023-04-02 17:33:35,051] {standard_task_runner.py:77} INFO - Job 202: Subtask process_data
[2023-04-02 17:33:35,125] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [running]> on host b24fa9ddb366
[2023-04-02 17:33:35,170] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mario
AIRFLOW_CTX_DAG_ID=dag_weather_etl_v02
AIRFLOW_CTX_TASK_ID=process_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-01T00:00:00+00:00
[2023-04-02 17:33:42,735] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py:238 FutureWarning: Python 3.6 support is deprecated in Spark 3.2.
[2023-04-02 17:33:44,784] {logging_mixin.py:104} INFO - La fecha 02/04/2023 18:00 no tiene el formato correcto
[2023-04-02 17:33:44,786] {logging_mixin.py:104} INFO - La fecha 02/04/2023 17:00 no tiene el formato correcto
[2023-04-02 17:33:44,787] {logging_mixin.py:104} INFO - La fecha 02/04/2023 16:00 no tiene el formato correcto
[2023-04-02 17:33:44,788] {logging_mixin.py:104} INFO - La fecha 02/04/2023 15:00 no tiene el formato correcto
[2023-04-02 17:33:44,789] {logging_mixin.py:104} INFO - La fecha 02/04/2023 14:00 no tiene el formato correcto
[2023-04-02 17:33:44,790] {logging_mixin.py:104} INFO - La fecha 02/04/2023 13:00 no tiene el formato correcto
[2023-04-02 17:33:44,791] {logging_mixin.py:104} INFO - La fecha 02/04/2023 12:00 no tiene el formato correcto
[2023-04-02 17:33:44,791] {logging_mixin.py:104} INFO - La fecha 02/04/2023 11:00 no tiene el formato correcto
[2023-04-02 17:33:44,792] {logging_mixin.py:104} INFO - La fecha 02/04/2023 10:00 no tiene el formato correcto
[2023-04-02 17:33:44,793] {logging_mixin.py:104} INFO - La fecha 02/04/2023 09:00 no tiene el formato correcto
[2023-04-02 17:33:44,794] {logging_mixin.py:104} INFO - La fecha 02/04/2023 08:00 no tiene el formato correcto
[2023-04-02 17:33:44,794] {logging_mixin.py:104} INFO - La fecha 02/04/2023 07:00 no tiene el formato correcto
[2023-04-02 17:33:44,795] {logging_mixin.py:104} INFO - La fecha 02/04/2023 06:00 no tiene el formato correcto
[2023-04-02 17:33:44,796] {logging_mixin.py:104} INFO - La fecha 02/04/2023 05:00 no tiene el formato correcto
[2023-04-02 17:33:44,796] {logging_mixin.py:104} INFO - La fecha 02/04/2023 04:00 no tiene el formato correcto
[2023-04-02 17:33:44,797] {logging_mixin.py:104} INFO - La fecha 02/04/2023 03:00 no tiene el formato correcto
[2023-04-02 17:33:44,798] {logging_mixin.py:104} INFO - La fecha 02/04/2023 02:00 no tiene el formato correcto
[2023-04-02 17:33:44,799] {logging_mixin.py:104} INFO - La fecha 02/04/2023 01:00 no tiene el formato correcto
[2023-04-02 17:33:44,801] {logging_mixin.py:104} INFO - La fecha 02/04/2023 00:00 no tiene el formato correcto
[2023-04-02 17:33:44,803] {logging_mixin.py:104} INFO - La fecha 01/04/2023 23:00 no tiene el formato correcto
[2023-04-02 17:33:44,805] {logging_mixin.py:104} INFO - La fecha 01/04/2023 22:00 no tiene el formato correcto
[2023-04-02 17:33:44,807] {logging_mixin.py:104} INFO - La fecha 01/04/2023 21:00 no tiene el formato correcto
[2023-04-02 17:33:44,809] {logging_mixin.py:104} INFO - La fecha 01/04/2023 20:00 no tiene el formato correcto
[2023-04-02 17:33:44,812] {logging_mixin.py:104} INFO - La fecha 01/04/2023 19:00 no tiene el formato correcto
[2023-04-02 17:33:46,233] {logging_mixin.py:104} WARNING - Traceback (most recent call last):
[2023-04-02 17:33:46,236] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/serializers.py", line 437, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
[2023-04-02 17:33:46,237] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
[2023-04-02 17:33:46,239] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
[2023-04-02 17:33:46,240] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
[2023-04-02 17:33:46,241] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 17:33:46,243] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
[2023-04-02 17:33:46,244] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 17:33:46,245] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
[2023-04-02 17:33:46,246] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 682, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
[2023-04-02 17:33:46,246] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
[2023-04-02 17:33:46,247] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 17:33:46,247] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
[2023-04-02 17:33:46,248] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 17:33:46,248] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
[2023-04-02 17:33:46,249] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
[2023-04-02 17:33:46,249] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/dill/_dill.py", line 1169, in save_cell
    f = obj.cell_contents
[2023-04-02 17:33:46,250] {logging_mixin.py:104} WARNING - ValueError: Cell is empty
[2023-04-02 17:33:46,252] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/serializers.py", line 437, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/usr/local/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 682, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
  File "/usr/local/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/local/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/airflow/.local/lib/python3.6/site-packages/dill/_dill.py", line 1169, in save_cell
    f = obj.cell_contents
ValueError: Cell is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_weather.py", line 76, in process_data
    spark_df = spark.createDataFrame(datos)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 674, in createDataFrame
    data, schema, samplingRatio, verifySchema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/pandas/conversion.py", line 340, in createDataFrame
    return self._create_dataframe(data, schema, samplingRatio, verifySchema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 701, in _create_dataframe
    jrdd = self._jvm.SerDeUtil.toJavaArray(rdd._to_java_object_rdd())
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/rdd.py", line 2620, in _to_java_object_rdd
    return self.ctx._jvm.SerDeUtil.pythonToJava(rdd._jrdd, True)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/rdd.py", line 2952, in _jrdd
    self._jrdd_deserializer, profiler)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/rdd.py", line 2830, in _wrap_function
    pickled_command, broadcast_vars, env, includes = _prepare_for_python_RDD(sc, command)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/rdd.py", line 2816, in _prepare_for_python_RDD
    pickled_command = ser.dumps(command)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/serializers.py", line 447, in dumps
    raise pickle.PicklingError(msg)
_pickle.PicklingError: Could not serialize object: ValueError: Cell is empty
[2023-04-02 17:33:46,263] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_weather_etl_v02, task_id=process_data, execution_date=20230401T000000, start_date=20230402T173334, end_date=20230402T173346
[2023-04-02 17:33:46,420] {local_task_job.py:146} INFO - Task exited with return code 1
