[2023-04-02 17:42:52,257] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [queued]>
[2023-04-02 17:42:52,308] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [queued]>
[2023-04-02 17:42:52,311] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 17:42:52,313] {taskinstance.py:1069} INFO - Starting attempt 8 of 13
[2023-04-02 17:42:52,316] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 17:42:52,412] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): process_data> on 2023-04-01T00:00:00+00:00
[2023-04-02 17:42:52,504] {standard_task_runner.py:52} INFO - Started process 938 to run task
[2023-04-02 17:42:52,515] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_weather_etl_v02', 'process_data', '2023-04-01T00:00:00+00:00', '--job-id', '205', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_weather.py', '--cfg-path', '/tmp/tmpk8eit_74', '--error-file', '/tmp/tmpvwh4uvy8']
[2023-04-02 17:42:52,517] {standard_task_runner.py:77} INFO - Job 205: Subtask process_data
[2023-04-02 17:42:52,620] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_weather_etl_v02.process_data 2023-04-01T00:00:00+00:00 [running]> on host b24fa9ddb366
[2023-04-02 17:42:52,682] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mario
AIRFLOW_CTX_DAG_ID=dag_weather_etl_v02
AIRFLOW_CTX_TASK_ID=process_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-01T00:00:00+00:00
[2023-04-02 17:43:00,201] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py:238 FutureWarning: Python 3.6 support is deprecated in Spark 3.2.
[2023-04-02 17:43:01,754] {logging_mixin.py:104} INFO - La fecha 02/04/2023 18:00 no tiene el formato correcto
[2023-04-02 17:43:01,756] {logging_mixin.py:104} INFO - La fecha 02/04/2023 17:00 no tiene el formato correcto
[2023-04-02 17:43:01,756] {logging_mixin.py:104} INFO - La fecha 02/04/2023 16:00 no tiene el formato correcto
[2023-04-02 17:43:01,757] {logging_mixin.py:104} INFO - La fecha 02/04/2023 15:00 no tiene el formato correcto
[2023-04-02 17:43:01,758] {logging_mixin.py:104} INFO - La fecha 02/04/2023 14:00 no tiene el formato correcto
[2023-04-02 17:43:01,758] {logging_mixin.py:104} INFO - La fecha 02/04/2023 13:00 no tiene el formato correcto
[2023-04-02 17:43:01,759] {logging_mixin.py:104} INFO - La fecha 02/04/2023 12:00 no tiene el formato correcto
[2023-04-02 17:43:01,759] {logging_mixin.py:104} INFO - La fecha 02/04/2023 11:00 no tiene el formato correcto
[2023-04-02 17:43:01,759] {logging_mixin.py:104} INFO - La fecha 02/04/2023 10:00 no tiene el formato correcto
[2023-04-02 17:43:01,760] {logging_mixin.py:104} INFO - La fecha 02/04/2023 09:00 no tiene el formato correcto
[2023-04-02 17:43:01,761] {logging_mixin.py:104} INFO - La fecha 02/04/2023 08:00 no tiene el formato correcto
[2023-04-02 17:43:01,761] {logging_mixin.py:104} INFO - La fecha 02/04/2023 07:00 no tiene el formato correcto
[2023-04-02 17:43:01,762] {logging_mixin.py:104} INFO - La fecha 02/04/2023 06:00 no tiene el formato correcto
[2023-04-02 17:43:01,762] {logging_mixin.py:104} INFO - La fecha 02/04/2023 05:00 no tiene el formato correcto
[2023-04-02 17:43:01,763] {logging_mixin.py:104} INFO - La fecha 02/04/2023 04:00 no tiene el formato correcto
[2023-04-02 17:43:01,763] {logging_mixin.py:104} INFO - La fecha 02/04/2023 03:00 no tiene el formato correcto
[2023-04-02 17:43:01,764] {logging_mixin.py:104} INFO - La fecha 02/04/2023 02:00 no tiene el formato correcto
[2023-04-02 17:43:01,764] {logging_mixin.py:104} INFO - La fecha 02/04/2023 01:00 no tiene el formato correcto
[2023-04-02 17:43:01,764] {logging_mixin.py:104} INFO - La fecha 02/04/2023 00:00 no tiene el formato correcto
[2023-04-02 17:43:01,765] {logging_mixin.py:104} INFO - La fecha 01/04/2023 23:00 no tiene el formato correcto
[2023-04-02 17:43:01,765] {logging_mixin.py:104} INFO - La fecha 01/04/2023 22:00 no tiene el formato correcto
[2023-04-02 17:43:01,766] {logging_mixin.py:104} INFO - La fecha 01/04/2023 21:00 no tiene el formato correcto
[2023-04-02 17:43:01,767] {logging_mixin.py:104} INFO - La fecha 01/04/2023 20:00 no tiene el formato correcto
[2023-04-02 17:43:01,767] {logging_mixin.py:104} INFO - La fecha 01/04/2023 19:00 no tiene el formato correcto
[2023-04-02 17:43:01,803] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_weather.py", line 76, in process_data
    spark_df = spark.createDataFrame(datos_procesados, schema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 674, in createDataFrame
    data, schema, samplingRatio, verifySchema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/pandas/conversion.py", line 340, in createDataFrame
    return self._create_dataframe(data, schema, samplingRatio, verifySchema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 700, in _create_dataframe
    rdd, schema = self._createFromLocal(map(prepare, data), schema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 509, in _createFromLocal
    data = list(data)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 682, in prepare
    verify_func(obj)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/types.py", line 1411, in verify
    verify_value(obj)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/types.py", line 1392, in verify_struct
    verifier(v)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/types.py", line 1411, in verify
    verify_value(obj)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/types.py", line 1405, in verify_default
    verify_acceptable_types(obj)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/types.py", line 1294, in verify_acceptable_types
    % (dataType, obj, type(obj))))
TypeError: field Fecha: TimestampType can not accept object '02/04/2023 18:00' in type <class 'str'>
[2023-04-02 17:43:01,810] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_weather_etl_v02, task_id=process_data, execution_date=20230401T000000, start_date=20230402T174252, end_date=20230402T174301
[2023-04-02 17:43:01,958] {local_task_job.py:146} INFO - Task exited with return code 1
