[2023-04-02 16:00:42,416] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v01.get_aemet_data 2023-03-24T00:00:00+00:00 [queued]>
[2023-04-02 16:00:42,523] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v01.get_aemet_data 2023-03-24T00:00:00+00:00 [queued]>
[2023-04-02 16:00:42,530] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 16:00:42,541] {taskinstance.py:1069} INFO - Starting attempt 3 of 6
[2023-04-02 16:00:42,542] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 16:00:42,619] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): get_aemet_data> on 2023-03-24T00:00:00+00:00
[2023-04-02 16:00:42,671] {standard_task_runner.py:52} INFO - Started process 211 to run task
[2023-04-02 16:00:42,687] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_weather_etl_v01', 'get_aemet_data', '2023-03-24T00:00:00+00:00', '--job-id', '127', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_weather.py', '--cfg-path', '/tmp/tmpy4vb8680', '--error-file', '/tmp/tmpktwym_ky']
[2023-04-02 16:00:42,689] {standard_task_runner.py:77} INFO - Job 127: Subtask get_aemet_data
[2023-04-02 16:00:42,851] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_weather_etl_v01.get_aemet_data 2023-03-24T00:00:00+00:00 [running]> on host ab4c74a9709c
[2023-04-02 16:00:43,026] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mario
AIRFLOW_CTX_DAG_ID=dag_weather_etl_v01
AIRFLOW_CTX_TASK_ID=get_aemet_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-24T00:00:00+00:00
[2023-04-02 16:00:45,098] {xcom.py:238} ERROR - Could not serialize the XCom value into JSON. If you are using pickles instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2023-04-02 16:00:45,112] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1344, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1928, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 88, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 235, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2023-04-02 16:00:45,127] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_weather_etl_v01, task_id=get_aemet_data, execution_date=20230324T000000, start_date=20230402T160042, end_date=20230402T160045
[2023-04-02 16:00:45,282] {local_task_job.py:146} INFO - Task exited with return code 1
