[2023-04-02 14:38:17,189] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v01.create_spark_session 2023-03-24T00:00:00+00:00 [queued]>
[2023-04-02 14:38:17,359] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_weather_etl_v01.create_spark_session 2023-03-24T00:00:00+00:00 [queued]>
[2023-04-02 14:38:17,361] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 14:38:17,364] {taskinstance.py:1069} INFO - Starting attempt 1 of 6
[2023-04-02 14:38:17,372] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 14:38:17,450] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): create_spark_session> on 2023-03-24T00:00:00+00:00
[2023-04-02 14:38:17,707] {standard_task_runner.py:52} INFO - Started process 68 to run task
[2023-04-02 14:38:17,844] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_weather_etl_v01', 'create_spark_session', '2023-03-24T00:00:00+00:00', '--job-id', '81', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_weather.py', '--cfg-path', '/tmp/tmp5rdxwf9k', '--error-file', '/tmp/tmpry8swvrc']
[2023-04-02 14:38:17,876] {standard_task_runner.py:77} INFO - Job 81: Subtask create_spark_session
[2023-04-02 14:38:18,690] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_weather_etl_v01.create_spark_session 2023-03-24T00:00:00+00:00 [running]> on host 225b241d8a3d
[2023-04-02 14:38:19,153] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mario
AIRFLOW_CTX_DAG_ID=dag_weather_etl_v01
AIRFLOW_CTX_TASK_ID=create_spark_session
AIRFLOW_CTX_EXECUTION_DATE=2023-03-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-24T00:00:00+00:00
[2023-04-02 14:38:24,087] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_weather.py", line 43, in create_spark_session
    .config("spark.sql.warehouse.dir", "/user/hive/warehouse")\
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py", line 392, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py", line 144, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py", line 339, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
    raise RuntimeError("Java gateway process exited before sending its port number")
RuntimeError: Java gateway process exited before sending its port number
[2023-04-02 14:38:24,341] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_weather_etl_v01, task_id=create_spark_session, execution_date=20230324T000000, start_date=20230402T143817, end_date=20230402T143824
[2023-04-02 14:38:25,209] {local_task_job.py:146} INFO - Task exited with return code 1
